### ISSUE TITLE
Early feedback request

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/enhance-visitors#1]
@sindresorhus @jamestalmage @twada I made this new repo to merge visitor objects, which we were doing a lot in `eslint-plugin-ava` and myself in `eslint-plugin-lodash-fp`.
This repo pretty much covers [this part](https://github.com/avajs/eslint-plugin-ava/blob/master/create-ava-rule.js#L112-L129), except that it allows you to merge more than two visitor objects (if someone has a better name...).

Being able to merge several would allow you to separate common logic even more, and make modules out of those. For example, we could have a module that collects all imports/top-level requires of a file are stores them in an object, available for querying.

Anyway, it's a nice logic that I use on multiple projects.

Now, I have two questions, which I'd like some feedback on:
1. `mergeVisitors` accepts an array of visitor objects. I found the rest argument too cumbersome to write when you want to reuse multiple enhancers, as you can't concatenante rest arguments easily.
2. I have also implemented [`ava.if`](https://github.com/avajs/eslint-plugin-ava/blob/master/create-ava-rule.js#L145) as `visitIf`. It "enhances" visitors and help to write rules, so I think it somewhat has its place, though I could also see it as an extra package, but I think it would be pretty hard to find on npm. This one also uses an array as argument rather than rest arguments. I have not documented it yet btw.

Thanks folks :)

**Comment by sindresorhus** [comment]
Looks good to me. Can you do a PR using it in eslint-plugin-ava?

**Comment by jfmengels** [comment]
Released v1.0.0.
